[bond-A]
interface = eth0
interface = eth1
tick  = 100 # Tick every 100ms, allows fast link drop
# pizza calzone
# pizza = yum
 # pizza = yum
a # b = c
d e = f

[bond-B]
interface = eth2
interface = eth3
tick  = 0 # No tick = only "normal" auto discovery
