DESTDIR?=/usr/local

.PHONY: default
default:
	# Run 'make install' to install this package

.PHONY: install
install: default
	install pmlag   $(DESTDIR)/bin
	install pmlag.1 $(DESTDIR)/share/man/man1

.PHONY: svc_openrc
svc_openrc: default
	DESTDIR=$(DESTDIR) envsubst < ./service/openrc/etc/init.d/pmlag > /etc/init.d/pmlag
	DESTDIR=$(DESTDIR) envsubst < ./service/common/etc/pmlag.ini    > /etc/pmlag.ini
	DESTDIR=$(DESTDIR) envsubst '$$DESTDIR' < ./service/openrc/etc/init.d/pmlag > svc
