---

name: Tag Assets
on:
  push:
    tags:
      - stable
      - edge

jobs:

  build-packages:
    name: Attach packages to release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            target: linux-glibc-amd64
            shell: /usr/bin/bash -e {0}
          - os: ubuntu-latest
            arch: x86_64
            target: linux-musl-amd64
            shell: alpine.sh {0}
    steps:
      - uses: actions/checkout@v3
      - uses: finwo/dep@edge
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.18
          arch: ${{ matrix.arch }}

      # TODO: run uraimo/run-on-arch-action@v2 for bash/glibc
      # TODO: run setup-alpine only for musl

      - name: Install pandoc
        run: ./.github/install-pkg.sh pandoc
        shell: ${{ matrix.shell }}

      - name: Build generic package
        run: make package TARGET=${{ matrix.target }} SVC=generic
        shell: ${{ matrix.shell }}

      - name: Build openrc package
        run: make package TARGET=${{ matrix.target }} SVC=openrc
        shell: ${{ matrix.shell }}

      - name: Build procd package
        run: make package TARGET=${{ matrix.target }} SVC=procd
        shell: ${{ matrix.shell }}

      - name: Upload packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ matrix.target }}/pmlag-*-${{ matrix.target }}.tar.gz
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
