---

name: Tag Assets
on:
  push:
    tags:
      - stable
      - edge

jobs:

  build-packages:
    name: Attach packages to release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            target: linux-glibc-amd64
            mode: native
          - os: ubuntu-latest
            arch: x86_64
            target: linux-musl-amd64
            mode: alpine
    steps:
      - uses: actions/checkout@v3
      - uses: jirutka/setup-alpine@v1
        if: ${{ matrix.mode == 'alpine' }}
        with:
          branch: v3.18
          arch: ${{ matrix.arch }}

      # TODO: run uraimo/run-on-arch-action@v2 for bash/glibc
      # TODO: run setup-alpine only for musl

      - if: ${{ matrix.mode == 'native' }}
        name: Install pandoc (native)
        run: ./.github/install-pkg.sh pandoc

      - if: ${{ matrix.mode == 'alpine' }}
        name: Install pandoc (alpine)
        shell: alpine.sh --root {0}
        run: |
          ./.github/install-pkg.sh bash
          ./.github/install-pkg.sh binutils
          ./.github/install-pkg.sh coreutils
          ./.github/install-pkg.sh pandoc
          ./.github/install-pkg.sh build-base
          ./.github/install-pkg.sh curl

      - uses: finwo/dep@edge
        name: Install dep (native)
        if: ${{ matrix.mode == 'native' }}

      - if: ${{ matrix.mode == 'alpine' }}
        name: Install dep (alpine)
        shell: alpine.sh --root {0}
        run: |
          curl -sSL https://raw.githubusercontent.com/finwo/dep/edge/dist/dep -o /usr/bin/dep
          chmod +x /usr/bin/dep

      - if: ${{ matrix.mode == 'native' }}
        name: Build generic package (native)
        run: |
          make package TARGET=${{ matrix.target }} SVC=generic
          make package TARGET=${{ matrix.target }} SVC=openrc
          make package TARGET=${{ matrix.target }} SVC=procd

      - if: ${{ matrix.mode == 'alpine' }}
        name: Build generic package (alpine)
        shell: alpine.sh {0}
        run: |
          make package TARGET=${{ matrix.target }} SVC=generic
          make package TARGET=${{ matrix.target }} SVC=openrc
          make package TARGET=${{ matrix.target }} SVC=procd

      - name: Upload packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ matrix.target }}/pmlag-*-${{ matrix.target }}.tar.gz
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
