---
name: Tag Assets
on:
  push:
    tags:
      - stable
      - edge

jobs:
  publish:
    name: Publish for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-glibc-amd64
          - os: alpine-latest
            target: linux-musl-amd64
    steps:
      - uses: actions/checkout@v3
      - uses: finwo/dep@edge
      - name: Build generic package
        run: make package SVC=generic
      - name: Build openrc package
        run: make package SVC=openrc
      - name: Build procd package
        run: make package SVC=procd
      - name: Upload packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ matrix.target }}/pmlag-*-${{ matrix.target }}.tar.gz
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
